### ISSUE TITLE
about the output shape in first layer

### ISSUE THREAD

**Issue by jackyLens** [HeewonChung92/CNN_LSTM_HeartRateEstimation#1]
waht does the number 6 mean in (none,2,222,1)?

**Comment by HeewonChung92** [comment]
This is our paper about [Deep Learning for Heart Rate Estimation From Reflectance Photoplethysmography With Acceleration Power Spectrum and Acceleration Intensity](https://ieeexplore.ieee.org/document/9042276).

The PPG signal and Acceleration signal are the time series data. 
The number 6 means window size. 
For example, the data size is N*222, we used the data indexing [0~6]*222, [1~7]*222, [2~8]*222, .... [N-6, N]*222.  (shifting 1 index)

**Comment by jackyLens** [comment]
Thank you, i have implemnted the NN.  
During the process, the preprocessing for signal ppg described in paper does not works well.
We modify the normalization for ppg.
we use the czt,rather than fft, in this way,the Butterworth filter can be discarded and the size of first layer is[ 6 * 2 * 200 * 1].

**Comment by HeewonChung92** [comment]
@jackyLens You can do it with your own research method. The FFT is just the method we used to get a clean HR signal.
