### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by wang-xiaoqiang** [HeewonChung92/CNN_LSTM_HeartRateEstimation#2]
Thank you for reading your article. Can you provide the source code？

**Comment by HeewonChung92** [comment]
Hello, Thank you for your interest.

I can't give you all the code, but I can give you the code for the models.
If you write your email address, I will send you a zip file. (related my models)

Have good luck for a new year 😃

**Comment by wang-xiaoqiang** [comment]
Thank you for taking the time to reply to me. . This is my email 434553477@qq.com . Thank you again

**Comment by liumiao-p** [comment]
Thank you for reply.I want the code too.My email is 857760294@qq.com, can you send me the code for the models?Thank you again.

**Comment by Daisy-Zhang** [comment]
Nice work! I am also interested in your project, could you send me the code to me? My email is daisy.zdcc@gmail.com. Thank you very much!

**Comment by HeewonChung92** [comment]
@Daisy-Zhang I sent you a reply email. Check it out.
