### ISSUE TITLE
Model issues

### ISSUE THREAD

**Issue by hansonzzz** [HeewonChung92/CNN_LSTM_HeartRateEstimation#4]
Hello, i am currently trying to create the model based on the architecture, summary and paper's model description but i am having issue following it. There are some parts that i don't understand quite well. Would it be possible to see the model's code to get a clearer understanding ?

**Comment by HeewonChung92** [comment]
Hello, Thank you for your interest.
I can't give you all the code, write your email address.

**Comment by hansonzzz** [comment]
Hello! Thank you for replying. My email address is hansonrobertus2@gmail.com

**Comment by JasminKer** [comment]
hello, thank  for this very interesting paper. Could you please send me the code to try yourour approach. Thank you sir
My e-mail is yasminekermoun1996@gmail.com

**Comment by svromanov** [comment]
Hello! Thank you for your paper! I'm currently trying to create the model, but have troubles with architecture. Would it be possible send me the code of model? my email is tisd101@gmail.com

**Comment by HeewonChung92** [comment]
@svromanov I'm sorry to see you late. I sent you a reply email. Check it out.
